"""Agent prompts — System prompts, reflection, templates."""

from src.agent.prompts.system import (
    AGENT_SYSTEM,
    CLASSIFIER_PROMPT,
    GENERATION_PROMPT,
    GENERATION_PROMPT_ANALYSIS,
    QUERY_PLANNER_PROMPT,
    REFLECTION_PROMPT,
    VALIDATOR_PROMPT,
)

__all__ = [
    "AGENT_SYSTEM",
    "GENERATION_PROMPT",
    "GENERATION_PROMPT_ANALYSIS",
    "REFLECTION_PROMPT",
    "CLASSIFIER_PROMPT",
    "QUERY_PLANNER_PROMPT",
    "VALIDATOR_PROMPT",
]
